### ISSUE TITLE
Does this library works on background thread?

### ISSUE THREAD

**Issue by klemenzagar91** [zacwest/ZSWTaggedString#10]
Hi, 
I want to know that in advance. Before I start using it?
Currencly i'm using native framework:
```
let attrStr = try! NSAttributedString(
      data: modifiedFont.data(using: .unicode, allowLossyConversion: true)!,
      options: [.documentType: NSAttributedString.DocumentType.html, .characterEncoding: String.Encoding.utf8.rawValue],
      documentAttributes: nil)
```
but it only works on main thread and it slows down the app a lot. I need the library that can create NSAttributedString on background thread.

**Comment by zacwest** [comment]
Yep, nothing about string generation touches UIKit so everything is allowed.
