### ISSUE TITLE
Swift 4.1 compatibility

### ISSUE THREAD

**Issue by anuragajwani** [zacwest/ZSWTaggedString#11]
Hi I have a problem when installing the ZSWTaggedString on Swift 4.1 project.

The version that I am using is 4.0.

```
- ZSWTaggedString/Core (4.0)
- ZSWTaggedString/Swift (4.0)
```

The pod is being configured to use `Swift 3.3`. 
<img width="778" alt="screen shot 2018-04-13 at 12 51 53" src="https://user-images.githubusercontent.com/7071488/38733493-eeddd192-3f19-11e8-9d8f-5f300bddea15.png">

Maybe the `.swift-version` file needs changing from `4.0` to `4.1` for compatibility with `Swift 4.1`?

Anurag

**Comment by zacwest** [comment]
Done in version 4.1.
