### ISSUE TITLE
img tag breaks the parsing

### ISSUE THREAD

**Issue by peterpaulis** [zacwest/ZSWTaggedString#17]
parsing this string results in     

`html = @"<p>telefonicky <a href=\"tel:+421948774999\" target=\"_blank\" style=\"color: rgb(38, 38, 38);\">+421 948 774 999</a> na recepcii. FYZIO KLINIK <img src=\"https://static.xx.fbcdn.net/images/emoji.php/v9/t56/2/16/1f917.png\"></p>";`

`String had ending tag /p when we expected ending tag img or new tag` even the `<img />` doesnt work

tags like that could be ignored at best

**Comment by zacwest** [comment]
In the general HTML-parsing sense, this is correct. However, this library isn't a 1:1 mapping of HTML to NSAttributedStrings; for that, you may want to look at [Apple's built-in HTML parsing](https://developer.apple.com/documentation/foundation/nsattributedstring/documentattributekey/1533961-documenttype#).

I think this could be a worthwhile addition to the ZSWTaggedStringOptions, to specify tags which aren't expected to be closed and thus ignored. It would need to be explicitly added, though.
