### ISSUE TITLE
Misplaced suffix

### ISSUE THREAD

**Issue by mtrubnikov** [zacwest/ZSWTaggedString#6]
After setting plain text with code suffix becomes misplaced:

<img width="289" alt="screenshot 2016-12-05 00 04 40" src="https://cloud.githubusercontent.com/assets/910299/20869598/71c691d8-ba7e-11e6-89d1-b403a1ea1da5.png">

**Comment by zacwest** [comment]
Does this only happen on e.g. iOS 10?

**Comment by zacwest** [comment]
I think perhaps you meant to post this in [ZSWSuffixTextView](https://github.com/zacwest/zswsuffixtextview) right?

**Comment by mtrubnikov** [comment]
Yes, you're right. Posted this here accidentally. Sorry for that.

**Comment by mtrubnikov** [comment]
Unfortunately, I've tested that issue only on iOS 10, so I can't say if this happens on other versions

**Comment by mtrubnikov** [comment]
Should I move that issue to [ZSWSuffixTextView](https://github.com/zacwest/zswsuffixtextview)?

**Comment by mtrubnikov** [comment]
Moved to ZSWSuffixTextView
