### ISSUE TITLE
ZSWStringParser.h:13:9: 'ZSWTaggedString/ZSWTaggedString.h' file not found

### ISSUE THREAD

**Issue by hzorr** [zacwest/ZSWTaggedString#7]
I'm using ZSWTaggedString in a swift 3 project, it started not to compile after cocoapod 1.1.1 update
with error:
ZSWStringParser.h:13:9: 'ZSWTaggedString/ZSWTaggedString.h' file not found

how to solve that issue?

**Comment by zacwest** [comment]
Please reopen if you're still experiencing this issue with version 3.0.
